### ISSUE TITLE
Breadcrumbs are not hyperlinked 

### ISSUE THREAD

**Issue by malikpiara** [upframe/internships#10]
In `https://internships.upframe.io/company/opportunity` the breadcrumbs are not hyperlinked yet. The `font-size` is also too big when compared with our zeplin files. Please take care of it!

**Comment by malikpiara** [comment]
<img width="1440" alt="screen shot 2018-12-13 at 18 26 07" src="https://user-images.githubusercontent.com/6923650/49956223-f75fc180-ff04-11e8-8760-bb50c67bbf29.png">
The last item of the breadcrumb is hyperlinked to `https://internships.upframe.io/company/`. When the user clicks there he's lead to a 404 page instead of the main page. Can we fix that?

**Comment by ulissesferreira** [comment]
This is almost done but it still missing one thing: the query when you click on a company will not follow the conventional get style. We should use something ".io/uniplaces" to make things easier and friendlier on the companies

**Comment by fabiofcferreira** [comment]
I guess we can say this issue is closed for now due to the fact that we don't have enough pages on our website.
Let's focus on getting those pages first so that we can make the **PEOPLE** navbar item redirects to `/people`.

Anyways, good point :+1:
